import {StyleSheet} from 'react-native';
import {isIOS} from '../../utils/deviceInfo';
import {
  COLOR_BLACK,
  COLOR_ERROR,
  COLOR_GRAY,
  COLOR_PRIMARY_500,
  COLOR_WHITE,
} from '../../constants/colors';

export default StyleSheet.create({
  topHeaderBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
  },
  container: {
    flex: 1,
    paddingVertical: 8,
  },
  firstZipCodeContainer: {
    backgroundColor: COLOR_WHITE,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    width: 160,
  },
  zipCodeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 8,
    paddingHorizontal: 16,
    width: 160,
  },
  zipCode: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '600',
    paddingRight: 8,
  },
  headerRightActions: {
    flexDirection: 'row',
  },
  headerRightIcon: {
    paddingHorizontal: 16,
  },
  topSwiper: {
    height: 170,
  },
  swiperContainer: {},
  dot: {
    backgroundColor: COLOR_GRAY,
    borderColor: COLOR_GRAY,
    borderWidth: 1,
    width: 4,
    height: 4,
    borderRadius: 2,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  activeDot: {
    backgroundColor: COLOR_PRIMARY_500,
    borderColor: COLOR_PRIMARY_500,
    borderWidth: 1,
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  slideItem: {
    backgroundColor: '#C4C4C4',
    borderRadius: 16,
    margin: 8,
    marginHorizontal: 16,
  },
  slideItemImage: {
    width: '100%',
    height: 150,
    borderRadius: 16,
    resizeMode: 'cover',
  },
  productCategories: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 8,
    justifyContent: 'flex-start',
    marginTop: 16,
    marginBottom: 24,
  },
  categoryContainer: {
    alignItems: 'center',
    width: '33%',
    marginBottom: 16,
  },
  categoryImageContent: {},
  categoryImage: {
    width: 104,
    height: 104,
    resizeMode: 'contain',
    borderRadius: isIOS ? 8 : 20,
  },
  categoryText: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    marginTop: 4,
    marginHorizontal: 10,
    textAlign: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: 360,
    borderRadius: 8,
    padding: 16,
    position: 'relative',
  },
  modalFirstContainer: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  formContainer: {
    flexDirection: 'row',
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
  },
  confirmContainer: {
    borderRadius: 32,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  confirmBtn: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '500',
    color: COLOR_WHITE,
  },
  errorZipCode: {
    color: COLOR_ERROR,
    marginTop: 8,
    fontSize: 14,
    lineHeight: 18,
  },
  arrowZipCode: {
    marginLeft: 48,
    width: 60,
    height: 130,
    resizeMode: 'contain',
  },
  helpZipCode: {
    color: COLOR_WHITE,
    marginTop: 12,
    alignSelf: 'center',
    fontSize: 20,
    fontWeight: '600',
    textAlign: 'center',
  },
  firstConfirmContainer: {
    marginTop: 32,
    borderRadius: 24,
    alignSelf: 'center',
  },
  firstConfirmBtn: {
    color: COLOR_BLACK,
    paddingVertical: 13,
    paddingHorizontal: 28,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '500',
  },
});
